title: Xiaozhen Ouyang Homepage
page-top-title: Xiaozhen Ouyang (欧阳潇桢)
top-section-bg-text: Economics
backgrounds:
  - static/assets/background/background_0.jpeg
  - static/assets/background/background_1.jpeg
background-interval-ms: 7000
background-overlay: 0.52
copyright-text: '&copy; Sen Li 2023-2026. All Rights Reserved.'
github-link:
  text: Github
  href: https://github.com/senli1073
license-link:
  text: License
  href: https://github.com/senli1073/senli1073.github.io/blob/main/LICENSE
sections:
  - id: home
    nav: HOME
    title: "Name | Xiaozhen Ouyang"
    href: '#page-top' # Default to '#<id>' if not specified
  - id: research
    nav: RESEARCH
    title: RESEARCH
    icon: bi-file-text-fill
  - id: awards
    nav: AWARDS
    title: AWARDS
    icon: bi-award-fill
